name: Deploy to NPM

on:
  push:
    branches:
      - nodejs-v14

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: echo "//registry.npmjs.org/:_authToken=${NPM_DEPLOY_TOKEN}" > .npmrc
        env:
          NPM_DEPLOY_TOKEN: ${{ secrets.NPM_DEPLOY_TOKEN }}
      - run: npm install
      - run: npm test
      # - run: npm publish --access public --tag nodejs-v14
      - run: echo "::set-env name=action_state::$(grep 'version' package.json | head -1 | awk -F':' '{ print $2 }' | sed 's/[",]//g')"
      - run: echo "$action_state"
      - run: PACKAGE_VERSION=$(grep 'version' package.json | head -1 | awk -F':' '{ print $2 }' | sed 's/[",]//g')
      - run: grep 'version' package.json
      - run: grep 'version' package.json | head -1
      - run: grep 'version' package.json | head -1 | awk -F':' '{ print $2 }'
      - run: grep 'version' package.json | head -1 | awk -F':' '{ print $2 }' | sed 's/[",]//g'
      - run: echo $PACKAGE_VERSION
      - run: npm dist-tag add create-typescript-project-dependencies@$PACKAGE_VERSION latest
